export const REPOSITORY = {
  USERS: 'USERS_REPOSITORY',
  LOGIN_SESSIONS: 'LOGIN_SESSIONS_REPOSITORY',
  PASSWORD_HISTORIES: 'PASSWORD_HISTORIES_REPOSITORY',
  PASSKEYS: 'PASSKEYS_REPOSITORY',
  ROLES: 'ROLES_REPOSITORY',
  PERMISSIONS: 'PERMISSIONS_REPOSITORY',
  ROLE_PERMISSIONS: 'ROLE_PERMISSIONS_REPOSITORY',

  // Accounting
  ACCOUNT_GROUPS: 'ACCOUNT_GROUPS_REPOSITORY',
  LEDGER_ACCOUNTS: 'LEDGER_ACCOUNTS_REPOSITORY',
  JOURNAL_ENTRIES: 'JOURNAL_ENTRIES_REPOSITORY',
  JOURNAL_ENTRY_LINES: 'JOURNAL_ENTRY_LINES_REPOSITORY',
  FINANCIAL_YEARS: 'FINANCIAL_YEARS_REPOSITORY',
  NUMBER_SEQUENCES: 'NUMBER_SEQUENCES_REPOSITORY',

  // Tax
  TAX_RATES: 'TAX_RATES_REPOSITORY',
  BUSINESS_SETTINGS: 'BUSINESS_SETTINGS_REPOSITORY',

  // Inventory
  CATEGORIES: 'CATEGORIES_REPOSITORY',
  UNITS: 'UNITS_REPOSITORY',
  HSN_CODES: 'HSN_CODES_REPOSITORY',
  PRODUCTS: 'PRODUCTS_REPOSITORY',
  STOCK_MOVEMENTS: 'STOCK_MOVEMENTS_REPOSITORY',
  STOCK_ADJUSTMENTS: 'STOCK_ADJUSTMENTS_REPOSITORY',
  STOCK_ADJUSTMENT_ITEMS: 'STOCK_ADJUSTMENT_ITEMS_REPOSITORY',

  // Parties
  PARTIES: 'PARTIES_REPOSITORY',

  // Banking
  BANK_ACCOUNTS: 'BANK_ACCOUNTS_REPOSITORY',
  BANK_TRANSACTIONS: 'BANK_TRANSACTIONS_REPOSITORY',
  PAYMENT_RECEIPTS: 'PAYMENT_RECEIPTS_REPOSITORY',
  PAYMENT_ALLOCATIONS: 'PAYMENT_ALLOCATIONS_REPOSITORY',

  // Purchases
  PURCHASE_BILLS: 'PURCHASE_BILLS_REPOSITORY',
  PURCHASE_BILL_ITEMS: 'PURCHASE_BILL_ITEMS_REPOSITORY',
  DEBIT_NOTES: 'DEBIT_NOTES_REPOSITORY',
  DEBIT_NOTE_ITEMS: 'DEBIT_NOTE_ITEMS_REPOSITORY',
  PURCHASE_ORDERS: 'PURCHASE_ORDERS_REPOSITORY',
  PURCHASE_ORDER_ITEMS: 'PURCHASE_ORDER_ITEMS_REPOSITORY',

  // Sales
  SALES_INVOICES: 'SALES_INVOICES_REPOSITORY',
  SALES_INVOICE_ITEMS: 'SALES_INVOICE_ITEMS_REPOSITORY',
  CREDIT_NOTES: 'CREDIT_NOTES_REPOSITORY',
  CREDIT_NOTE_ITEMS: 'CREDIT_NOTE_ITEMS_REPOSITORY',
  QUOTATIONS: 'QUOTATIONS_REPOSITORY',
  QUOTATION_ITEMS: 'QUOTATION_ITEMS_REPOSITORY',

  // POS
  POS_TERMINALS: 'POS_TERMINALS_REPOSITORY',
  POS_SESSIONS: 'POS_SESSIONS_REPOSITORY',
  HELD_BILLS: 'HELD_BILLS_REPOSITORY',
} as const;

export const AUTH_PROVIDER = {
  LOCAL: 'local',
  GOOGLE: 'google',
} as const;

export const MFA_METHOD = {
  EMAIL: 'email',
  TOTP: 'totp',
} as const;
