export const SEED_USERS = [
  {
    email: 'admin@example.com',
    password: 'Admin@1234',
    first_name: 'Admin',
    last_name: 'User',
    phone: '+1234567890',
    timezone: 'America/New_York',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'john@example.com',
    password: 'John@1234',
    first_name: 'John',
    last_name: 'Doe',
    phone: '+1987654321',
    timezone: 'Europe/London',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'jane@example.com',
    password: 'Jane@1234',
    first_name: 'Jane',
    last_name: 'Smith',
    phone: '+1122334455',
    timezone: 'Asia/Tokyo',
    language: 'en',
    email_verified: false,
  },
  {
    email: 'michael.brown@example.com',
    password: 'Michael@1234',
    first_name: 'Michael',
    last_name: 'Brown',
    phone: '+1445566778',
    timezone: 'America/Chicago',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'emily.wilson@example.com',
    password: 'Emily@1234',
    first_name: 'Emily',
    last_name: 'Wilson',
    phone: '+1556677889',
    timezone: 'America/Los_Angeles',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'david.taylor@example.com',
    password: 'David@1234',
    first_name: 'David',
    last_name: 'Taylor',
    phone: '+4471234567',
    timezone: 'Europe/London',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'sophia.martinez@example.com',
    password: 'Sophia@1234',
    first_name: 'Sophia',
    last_name: 'Martinez',
    phone: '+3491234567',
    timezone: 'Europe/Madrid',
    language: 'es',
    email_verified: false,
  },
  {
    email: 'james.anderson@example.com',
    password: 'James@1234',
    first_name: 'James',
    last_name: 'Anderson',
    phone: '+6141234567',
    timezone: 'Australia/Sydney',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'olivia.thomas@example.com',
    password: 'Olivia@1234',
    first_name: 'Olivia',
    last_name: 'Thomas',
    phone: '+3312345678',
    timezone: 'Europe/Paris',
    language: 'fr',
    email_verified: true,
  },
  {
    email: 'william.jackson@example.com',
    password: 'William@1234',
    first_name: 'William',
    last_name: 'Jackson',
    phone: '+1667788990',
    timezone: 'America/Denver',
    language: 'en',
    email_verified: false,
  },
  {
    email: 'ava.white@example.com',
    password: 'Ava@1234',
    first_name: 'Ava',
    last_name: 'White',
    phone: '+4930123456',
    timezone: 'Europe/Berlin',
    language: 'de',
    email_verified: true,
  },
  {
    email: 'alexander.harris@example.com',
    password: 'Alex@1234',
    first_name: 'Alexander',
    last_name: 'Harris',
    phone: '+8112345678',
    timezone: 'Asia/Tokyo',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'mia.clark@example.com',
    password: 'Mia@12345',
    first_name: 'Mia',
    last_name: 'Clark',
    phone: '+1778899001',
    timezone: 'America/New_York',
    language: 'en',
    email_verified: false,
  },
  {
    email: 'ethan.lewis@example.com',
    password: 'Ethan@1234',
    first_name: 'Ethan',
    last_name: 'Lewis',
    phone: '+5511987654',
    timezone: 'America/Sao_Paulo',
    language: 'pt',
    email_verified: true,
  },
  {
    email: 'isabella.robinson@example.com',
    password: 'Isabella@1234',
    first_name: 'Isabella',
    last_name: 'Robinson',
    phone: '+3901234567',
    timezone: 'Europe/Rome',
    language: 'it',
    email_verified: true,
  },
  {
    email: 'daniel.walker@example.com',
    password: 'Daniel@1234',
    first_name: 'Daniel',
    last_name: 'Walker',
    phone: '+1889900112',
    timezone: 'America/Chicago',
    language: 'en',
    email_verified: false,
  },
  {
    email: 'charlotte.hall@example.com',
    password: 'Charlotte@1234',
    first_name: 'Charlotte',
    last_name: 'Hall',
    phone: '+6421234567',
    timezone: 'Pacific/Auckland',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'henry.allen@example.com',
    password: 'Henry@1234',
    first_name: 'Henry',
    last_name: 'Allen',
    phone: '+4161234567',
    timezone: 'America/Toronto',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'amelia.young@example.com',
    password: 'Amelia@1234',
    first_name: 'Amelia',
    last_name: 'Young',
    phone: '+9112345678',
    timezone: 'Asia/Kolkata',
    language: 'en',
    email_verified: false,
  },
  {
    email: 'sebastian.king@example.com',
    password: 'Sebastian@1234',
    first_name: 'Sebastian',
    last_name: 'King',
    phone: '+4612345678',
    timezone: 'Europe/Stockholm',
    language: 'sv',
    email_verified: true,
  },
  {
    email: 'harper.wright@example.com',
    password: 'Harper@1234',
    first_name: 'Harper',
    last_name: 'Wright',
    phone: '+8212345678',
    timezone: 'Asia/Seoul',
    language: 'ko',
    email_verified: true,
  },
  {
    email: 'lucas.scott@example.com',
    password: 'Lucas@1234',
    first_name: 'Lucas',
    last_name: 'Scott',
    phone: '+3161234567',
    timezone: 'Europe/Amsterdam',
    language: 'nl',
    email_verified: false,
  },
  {
    email: 'ella.green@example.com',
    password: 'Ella@1234',
    first_name: 'Ella',
    last_name: 'Green',
    phone: '+3531234567',
    timezone: 'Europe/Dublin',
    language: 'en',
    email_verified: true,
  },
];
