export const SEED_USERS = [
  {
    email: 'admin@example.com',
    password: 'Admin@1234',
    first_name: 'Admin',
    last_name: 'User',
    phone: '+1234567890',
    timezone: 'America/New_York',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'john@example.com',
    password: 'John@1234',
    first_name: 'John',
    last_name: 'Doe',
    phone: '+1987654321',
    timezone: 'Europe/London',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'jane@example.com',
    password: 'Jane@1234',
    first_name: 'Jane',
    last_name: 'Smith',
    phone: '+1122334455',
    timezone: 'Asia/Tokyo',
    language: 'en',
    email_verified: false,
  },
  {
    email: 'michael.brown@example.com',
    password: 'Michael@1234',
    first_name: 'Michael',
    last_name: 'Brown',
    phone: '+1445566778',
    timezone: 'America/Chicago',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'emily.wilson@example.com',
    password: 'Emily@1234',
    first_name: 'Emily',
    last_name: 'Wilson',
    phone: '+1556677889',
    timezone: 'America/Los_Angeles',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'david.taylor@example.com',
    password: 'David@1234',
    first_name: 'David',
    last_name: 'Taylor',
    phone: '+4471234567',
    timezone: 'Europe/London',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'sophia.martinez@example.com',
    password: 'Sophia@1234',
    first_name: 'Sophia',
    last_name: 'Martinez',
    phone: '+3491234567',
    timezone: 'Europe/Madrid',
    language: 'es',
    email_verified: false,
  },
  {
    email: 'james.anderson@example.com',
    password: 'James@1234',
    first_name: 'James',
    last_name: 'Anderson',
    phone: '+6141234567',
    timezone: 'Australia/Sydney',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'olivia.thomas@example.com',
    password: 'Olivia@1234',
    first_name: 'Olivia',
    last_name: 'Thomas',
    phone: '+3312345678',
    timezone: 'Europe/Paris',
    language: 'fr',
    email_verified: true,
  },
  {
    email: 'william.jackson@example.com',
    password: 'William@1234',
    first_name: 'William',
    last_name: 'Jackson',
    phone: '+1667788990',
    timezone: 'America/Denver',
    language: 'en',
    email_verified: false,
  },
  {
    email: 'ava.white@example.com',
    password: 'Ava@1234',
    first_name: 'Ava',
    last_name: 'White',
    phone: '+4930123456',
    timezone: 'Europe/Berlin',
    language: 'de',
    email_verified: true,
  },
  {
    email: 'alexander.harris@example.com',
    password: 'Alex@1234',
    first_name: 'Alexander',
    last_name: 'Harris',
    phone: '+8112345678',
    timezone: 'Asia/Tokyo',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'mia.clark@example.com',
    password: 'Mia@12345',
    first_name: 'Mia',
    last_name: 'Clark',
    phone: '+1778899001',
    timezone: 'America/New_York',
    language: 'en',
    email_verified: false,
  },
  {
    email: 'ethan.lewis@example.com',
    password: 'Ethan@1234',
    first_name: 'Ethan',
    last_name: 'Lewis',
    phone: '+5511987654',
    timezone: 'America/Sao_Paulo',
    language: 'pt',
    email_verified: true,
  },
  {
    email: 'isabella.robinson@example.com',
    password: 'Isabella@1234',
    first_name: 'Isabella',
    last_name: 'Robinson',
    phone: '+3901234567',
    timezone: 'Europe/Rome',
    language: 'it',
    email_verified: true,
  },
  {
    email: 'daniel.walker@example.com',
    password: 'Daniel@1234',
    first_name: 'Daniel',
    last_name: 'Walker',
    phone: '+1889900112',
    timezone: 'America/Chicago',
    language: 'en',
    email_verified: false,
  },
  {
    email: 'charlotte.hall@example.com',
    password: 'Charlotte@1234',
    first_name: 'Charlotte',
    last_name: 'Hall',
    phone: '+6421234567',
    timezone: 'Pacific/Auckland',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'henry.allen@example.com',
    password: 'Henry@1234',
    first_name: 'Henry',
    last_name: 'Allen',
    phone: '+4161234567',
    timezone: 'America/Toronto',
    language: 'en',
    email_verified: true,
  },
  {
    email: 'amelia.young@example.com',
    password: 'Amelia@1234',
    first_name: 'Amelia',
    last_name: 'Young',
    phone: '+9112345678',
    timezone: 'Asia/Kolkata',
    language: 'en',
    email_verified: false,
  },
  {
    email: 'sebastian.king@example.com',
    password: 'Sebastian@1234',
    first_name: 'Sebastian',
    last_name: 'King',
    phone: '+4612345678',
    timezone: 'Europe/Stockholm',
    language: 'sv',
    email_verified: true,
  },
  {
    email: 'harper.wright@example.com',
    password: 'Harper@1234',
    first_name: 'Harper',
    last_name: 'Wright',
    phone: '+8212345678',
    timezone: 'Asia/Seoul',
    language: 'ko',
    email_verified: true,
  },
  {
    email: 'lucas.scott@example.com',
    password: 'Lucas@1234',
    first_name: 'Lucas',
    last_name: 'Scott',
    phone: '+3161234567',
    timezone: 'Europe/Amsterdam',
    language: 'nl',
    email_verified: false,
  },
  {
    email: 'ella.green@example.com',
    password: 'Ella@1234',
    first_name: 'Ella',
    last_name: 'Green',
    phone: '+3531234567',
    timezone: 'Europe/Dublin',
    language: 'en',
    email_verified: true,
  },
];

// ─── Accounting Seed Data ──────────────────────────────────

/**
 * Account Groups — hierarchical chart of accounts structure.
 * Each child references its parent's `name` (resolved at seed time).
 */
export const SEED_ACCOUNT_GROUPS = [
  // Root groups
  { name: 'Assets', nature: 'assets', parent: null, is_system: true, sequence: 1 },
  { name: 'Liabilities', nature: 'liabilities', parent: null, is_system: true, sequence: 2 },
  { name: 'Income', nature: 'income', parent: null, is_system: true, sequence: 3 },
  { name: 'Expenses', nature: 'expense', parent: null, is_system: true, sequence: 4 },
  { name: 'Equity', nature: 'equity', parent: null, is_system: true, sequence: 5 },

  // Assets sub-groups
  { name: 'Current Assets', nature: 'assets', parent: 'Assets', is_system: true, sequence: 1 },
  { name: 'Fixed Assets', nature: 'assets', parent: 'Assets', is_system: true, sequence: 2 },
  { name: 'Cash & Bank', nature: 'assets', parent: 'Current Assets', is_system: true, sequence: 1 },
  { name: 'Sundry Debtors', nature: 'assets', parent: 'Current Assets', is_system: true, sequence: 2 },
  { name: 'Inventory', nature: 'assets', parent: 'Current Assets', is_system: true, sequence: 3 },
  { name: 'GST Input Credit', nature: 'assets', parent: 'Current Assets', is_system: true, sequence: 4 },

  // Liabilities sub-groups
  { name: 'Current Liabilities', nature: 'liabilities', parent: 'Liabilities', is_system: true, sequence: 1 },
  { name: 'Long-term Liabilities', nature: 'liabilities', parent: 'Liabilities', is_system: true, sequence: 2 },
  { name: 'Sundry Creditors', nature: 'liabilities', parent: 'Current Liabilities', is_system: true, sequence: 1 },
  { name: 'GST Output Liability', nature: 'liabilities', parent: 'Current Liabilities', is_system: true, sequence: 2 },
  { name: 'Duties & Taxes', nature: 'liabilities', parent: 'Current Liabilities', is_system: true, sequence: 3 },
  { name: 'Other Current Liabilities', nature: 'liabilities', parent: 'Current Liabilities', is_system: true, sequence: 4 },

  // Income sub-groups
  { name: 'Direct Income', nature: 'income', parent: 'Income', is_system: true, sequence: 1 },
  { name: 'Indirect Income', nature: 'income', parent: 'Income', is_system: true, sequence: 2 },

  // Expense sub-groups
  { name: 'Direct Expenses', nature: 'expense', parent: 'Expenses', is_system: true, sequence: 1 },
  { name: 'Indirect Expenses', nature: 'expense', parent: 'Expenses', is_system: true, sequence: 2 },

  // Equity sub-groups
  { name: 'Capital Account', nature: 'equity', parent: 'Equity', is_system: true, sequence: 1 },
  { name: 'Reserves & Surplus', nature: 'equity', parent: 'Equity', is_system: true, sequence: 2 },
];

/**
 * System Ledger Accounts — auto-created, referenced by transaction modules.
 * `group` refers to the account group name from SEED_ACCOUNT_GROUPS.
 */
export const SEED_LEDGER_ACCOUNTS = [
  { name: 'Cash in Hand', group: 'Cash & Bank', is_system: true },
  { name: 'Sales Account', group: 'Direct Income', is_system: true },
  { name: 'Purchase Account', group: 'Direct Expenses', is_system: true },
  { name: 'CGST Input', group: 'GST Input Credit', is_system: true },
  { name: 'SGST Input', group: 'GST Input Credit', is_system: true },
  { name: 'IGST Input', group: 'GST Input Credit', is_system: true },
  { name: 'CGST Output', group: 'GST Output Liability', is_system: true },
  { name: 'SGST Output', group: 'GST Output Liability', is_system: true },
  { name: 'IGST Output', group: 'GST Output Liability', is_system: true },
  { name: 'Discount Allowed', group: 'Indirect Expenses', is_system: true },
  { name: 'Discount Received', group: 'Indirect Income', is_system: true },
  { name: 'Round Off', group: 'Indirect Expenses', is_system: true },
  { name: 'Stock-in-Hand', group: 'Inventory', is_system: true },
  { name: 'Stock Adjustment', group: 'Indirect Expenses', is_system: true },
];

// ─── Tax Seed Data ──────────────────────────────────

// ─── Inventory Seed Data ──────────────────────────────────

export const SEED_UNITS = [
  { name: 'Pieces', short_name: 'PCS' },
  { name: 'Kilograms', short_name: 'KG' },
  { name: 'Grams', short_name: 'G' },
  { name: 'Liters', short_name: 'LTR' },
  { name: 'Milliliters', short_name: 'ML' },
  { name: 'Meters', short_name: 'MTR' },
  { name: 'Centimeters', short_name: 'CM' },
  { name: 'Box', short_name: 'BOX' },
  { name: 'Pack', short_name: 'PCK' },
  { name: 'Dozen', short_name: 'DZN' },
  { name: 'Pair', short_name: 'PR' },
  { name: 'Set', short_name: 'SET' },
  { name: 'Bag', short_name: 'BAG' },
  { name: 'Bottle', short_name: 'BTL' },
  { name: 'Roll', short_name: 'ROL' },
  { name: 'Square Feet', short_name: 'SQF' },
  { name: 'Square Meters', short_name: 'SQM' },
  { name: 'Numbers', short_name: 'NOS' },
];

export const SEED_TAX_RATES = [
  { name: 'Exempt', rate: 0, cgst_rate: 0, sgst_rate: 0, igst_rate: 0, cess_rate: 0 },
  { name: 'GST 5%', rate: 5, cgst_rate: 2.5, sgst_rate: 2.5, igst_rate: 5, cess_rate: 0 },
  { name: 'GST 12%', rate: 12, cgst_rate: 6, sgst_rate: 6, igst_rate: 12, cess_rate: 0 },
  { name: 'GST 18%', rate: 18, cgst_rate: 9, sgst_rate: 9, igst_rate: 18, cess_rate: 0 },
  { name: 'GST 28%', rate: 28, cgst_rate: 14, sgst_rate: 14, igst_rate: 28, cess_rate: 0 },
];
